### ISSUE TITLE
Unable to create Webhook

### ISSUE THREAD

**Issue by rserna2010** [finix-payments/processing-php-client#39]
```php
<?php

require_once('vendor/autoload.php');
require(__DIR__ . '/src/Finix/Settings.php');

Finix\Settings::configure([
  "root_url" => 'https://api-staging.finix.io',
  "username" => 'USuun62WjqPJoKGKUiRCg1VW',
  "password" => '104b0fe0-edff-44a4-b240-695bd2b500c6']
  );

require(__DIR__ . '/src/Finix/Bootstrap.php');
Finix\Bootstrap::init();

use Finix\Resources\Webhook;

$webhook = new Webhook(
      array(
      "url"=> "www.12321.com"
  ));
$webhook = $webhook->save();
```

results in:
```
atal error: Uncaught exception 'Finix\Hal\Exception\HalClientErrorException' with message '[url] https://api-staging.finix.io/webhooks [http method] POST [status code] 400 [reason phrase] Bad Request: {
  "total" : 1,
  "_embedded" : {
    "errors" : [ {
      "logref" : "f2af58ce-62be-40de-8966-ea991057ffe7",
      "message" : "Malformed request. ",
      "code" : "BAD_REQUEST",
      "_links" : {
        "self" : {
          "href" : "http://api-staging.finix.io/webhooks"
        }
      }
    } ]
  }
}' in /Users/richardserna2/Code/very_good/processing-php-client/src/Finix/Hal/Client.php:136
Stack trace:
#0 /Users/richardserna2/Code/very_good/processing-php-client/src/Finix/Resource.php(166): Finix\Hal\Client->sendRequest(Object(Finix\Http\Request))
#1 /Users/richardserna2/Code/very_good/processing-php-client/example-snippets.php(110): Finix\Resource->save()
#2 {main}
  thrown in /Users/richardserna2/Code/very_good/processing-php-client/src/Finix/Hal/Client.php on line 136
```

**Comment by rserna2010** [comment]
NVM looks like a issue in the API
